[package]
name = "track2line_lib"
version = "0.6.0"
edition = "2021"

[features]
default = []
experimental = []

[dependencies]
# deepspeech = "0.9.1"
# simple_transcribe_rs = "1.0.3"
tokio = "1.44.0"
whisper-rs = "0.14.2"
rodio = "0.20.1"

